import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1786211540013 implements MigrationInterface {
    name = 'Baseline1786211540013'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."project_activity_entitytype_enum" AS ENUM('project', 'team', 'sprint', 'work_item')`);
        await queryRunner.query(`CREATE TYPE "public"."project_activity_action_enum" AS ENUM('created', 'updated', 'state_changed', 'assigned', 'unassigned', 'deleted', 'work_logged', 'member_added', 'member_removed', 'access_changed', 'sprint_changed')`);
        await queryRunner.query(`CREATE TABLE "project_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" character varying NOT NULL, "entityType" "public"."project_activity_entitytype_enum" NOT NULL, "entityId" character varying NOT NULL, "entityTitle" character varying, "action" "public"."project_activity_action_enum" NOT NULL, "actorId" character varying, "actorName" character varying, "changes" text, "summary" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1d722fe8898deff9b95ba377a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_093560da4ec93f917bf26a1528" ON "project_activity"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b8da19d753f3f5cb79f4b6f2d" ON "project_activity"  ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d35666b9fca3fbfabba4c5ebb9" ON "project_activity"  ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."regularizations_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "regularizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "requestedCheckIn" TIMESTAMP, "requestedCheckOut" TIMESTAMP, "reason" text NOT NULL, "status" "public"."regularizations_status_enum" NOT NULL DEFAULT 'pending', "approvedById" character varying, "decidedAt" TIMESTAMP, "decisionNote" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "employeeId" uuid, CONSTRAINT "PK_51882a1b9f885cb7d82d596f243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_787ad05f1678689230c5e7f7b4" ON "regularizations"  ("employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('active', 'on_hold', 'completed')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'active', "startDate" date, "targetDate" date, "color" character varying, "ownerId" character varying, "ownerName" character varying, "updatedById" character varying, "updatedByName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63e67599567b2126cfef14e147" ON "projects"  ("key") `);
        await queryRunner.query(`CREATE TABLE "project_teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "managerEmployeeId" character varying, "managerName" character varying, "createdById" character varying, "createdByName" character varying, "updatedById" character varying, "updatedByName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01a9679008fec32d42fe331ff10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d71c230aff02473fe1ecb50942" ON "project_teams"  ("projectId") `);
        await queryRunner.query(`CREATE TYPE "public"."project_team_members_accesslevel_enum" AS ENUM('read', 'contribute', 'manage')`);
        await queryRunner.query(`CREATE TABLE "project_team_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teamId" character varying NOT NULL, "projectId" character varying NOT NULL, "employeeId" character varying NOT NULL, "name" character varying NOT NULL, "role" character varying, "accessLevel" "public"."project_team_members_accesslevel_enum" NOT NULL DEFAULT 'contribute', "capacityHoursPerDay" double precision NOT NULL DEFAULT '8', "addedById" character varying, "addedByName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005000583312b398393c8296d18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de336dd3979a38724d58ae30d8" ON "project_team_members"  ("teamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f3370a56d2658d30d7583cf12" ON "project_team_members"  ("projectId") `);
        await queryRunner.query(`CREATE TYPE "public"."project_sprints_status_enum" AS ENUM('future', 'current', 'completed')`);
        await queryRunner.query(`CREATE TABLE "project_sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" character varying NOT NULL, "teamId" character varying, "name" character varying NOT NULL, "goal" text, "startDate" date NOT NULL, "endDate" date NOT NULL, "status" "public"."project_sprints_status_enum" NOT NULL DEFAULT 'future', "createdById" character varying, "createdByName" character varying, "updatedById" character varying, "updatedByName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5890ebf9be7d182f1d88369e7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bce318acbb09dabc770bc4991c" ON "project_sprints"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1199343c652931a1f14a8c0387" ON "project_sprints"  ("teamId") `);
        await queryRunner.query(`CREATE TYPE "public"."work_items_type_enum" AS ENUM('epic', 'feature', 'user_story', 'task', 'bug')`);
        await queryRunner.query(`CREATE TYPE "public"."work_items_state_enum" AS ENUM('new', 'active', 'resolved', 'closed', 'removed')`);
        await queryRunner.query(`CREATE TABLE "work_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seq" integer NOT NULL DEFAULT '1', "projectId" character varying NOT NULL, "sprintId" character varying, "teamId" character varying, "parentId" character varying, "type" "public"."work_items_type_enum" NOT NULL, "title" character varying NOT NULL, "description" text, "state" "public"."work_items_state_enum" NOT NULL DEFAULT 'new', "reason" character varying, "priority" integer NOT NULL DEFAULT '2', "assigneeId" character varying, "assigneeName" character varying, "storyPoints" double precision NOT NULL DEFAULT '0', "originalEstimate" double precision NOT NULL DEFAULT '0', "remainingWork" double precision NOT NULL DEFAULT '0', "completedWork" double precision NOT NULL DEFAULT '0', "tags" text, "createdById" character varying, "createdByName" character varying, "updatedById" character varying, "updatedByName" character varying, "startDate" date, "targetDate" date, "activatedAt" TIMESTAMP, "resolvedAt" TIMESTAMP, "closedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_work_item_project_seq" UNIQUE ("projectId", "seq"), CONSTRAINT "PK_afbfa01728533c866eafaf6f160" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5389d5a18c0058c26f949c3ace" ON "work_items"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cb8969d4f4b12b18bfbefc373" ON "work_items"  ("sprintId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0af3ac60fd4ce701702a331f9d" ON "work_items"  ("teamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_abeae3c5eda0582b40f441724d" ON "work_items"  ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82807b63980b71887811dd3e2b" ON "work_items"  ("assigneeId") `);
        await queryRunner.query(`CREATE TABLE "work_item_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workItemId" character varying NOT NULL, "projectId" character varying NOT NULL, "employeeId" character varying NOT NULL, "employeeName" character varying, "hours" double precision NOT NULL, "date" date NOT NULL, "note" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c90188c0fef92d1ea4d51d75b0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f11650589e0d7eb7430074c0ef" ON "work_item_logs"  ("workItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea1447da1c15277f0d6e6bc306" ON "work_item_logs"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_970ffad745900038e0940bbc81" ON "work_item_logs"  ("employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."calendar_events_meetingmode_enum" AS ENUM('Online', 'Offline', 'Hybrid')`);
        await queryRunner.query(`CREATE TYPE "public"."calendar_events_recurrencetype_enum" AS ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TYPE "public"."calendar_events_status_enum" AS ENUM('SCHEDULED', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("eventId" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "description" character varying(500), "organizerId" uuid NOT NULL, "startDateTime" TIMESTAMP NOT NULL, "endDateTime" TIMESTAMP NOT NULL, "meetingMode" "public"."calendar_events_meetingmode_enum" NOT NULL, "location" character varying, "meetingLink" character varying, "recurrenceType" "public"."calendar_events_recurrencetype_enum" NOT NULL DEFAULT 'NONE', "recurrenceEndDate" date, "status" "public"."calendar_events_status_enum" NOT NULL DEFAULT 'SCHEDULED', "createdById" uuid NOT NULL, "updatedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_78a7ec5e4c6be72dfa19b59ecd9" PRIMARY KEY ("eventId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a007ca3d443825b41461d9da45" ON "calendar_events"  ("organizerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_69b9c4cb2cb4a6cf03bb035206" ON "calendar_events"  ("startDateTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_7dcd288f71e9aececacecd48a9" ON "calendar_events"  ("endDateTime") `);
        await queryRunner.query(`CREATE TYPE "public"."event_participants_responsestatus_enum" AS ENUM('Pending', 'Accepted', 'Declined', 'Tentative')`);
        await queryRunner.query(`CREATE TABLE "event_participants" ("participantId" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventId" uuid NOT NULL, "employeeId" uuid NOT NULL, "responseStatus" "public"."event_participants_responsestatus_enum" NOT NULL DEFAULT 'Pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "respondedAt" TIMESTAMP, CONSTRAINT "PK_835950d443e6f956a5d32150a07" PRIMARY KEY ("participantId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4907f15416577c3bbbcd604d12" ON "event_participants"  ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c9dcc59e626ce14da4adbfc29" ON "event_participants"  ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aaf80b5186beed4e37b9ba7cb8" ON "event_participants"  ("eventId", "employeeId") `);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetAttempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "readAt" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'SENT'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "attempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "occurrenceAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "sentAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" ADD VALUE 'calendar_invite'`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" ADD VALUE 'calendar_update'`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" ADD VALUE 'calendar_cancel'`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" ADD VALUE 'calendar_reminder'`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" ADD VALUE 'work_item'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa00ce161b51b02fdf992ea952" ON "employees"  ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_07731c02b0333dc9b2678f9821" ON "attendance"  ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff05fd5159e6d9d99514d46531" ON "attendance"  ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_employee_date" ON "attendance"  ("employeeId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3337493bfdc5d0fccd4bd5f51e" ON "notifications"  ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eeffbd86fba74517d4dacc8ab3" ON "payrolls"  ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4278e2dd5d9673eac18b6ab6f" ON "leaves"  ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_employee_start" ON "leaves"  ("employeeId", "startDate") `);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD CONSTRAINT "uq_payroll_employee_period" UNIQUE ("employeeId", "month", "year")`);
        await queryRunner.query(`ALTER TABLE "regularizations" ADD CONSTRAINT "FK_787ad05f1678689230c5e7f7b4f" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "regularizations" DROP CONSTRAINT "FK_787ad05f1678689230c5e7f7b4f"`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP CONSTRAINT "uq_payroll_employee_period"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_employee_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4278e2dd5d9673eac18b6ab6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeffbd86fba74517d4dacc8ab3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3337493bfdc5d0fccd4bd5f51e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendance_employee_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff05fd5159e6d9d99514d46531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07731c02b0333dc9b2678f9821"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa00ce161b51b02fdf992ea952"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum_old" AS ENUM('info', 'approval', 'leave', 'payroll', 'ticket', 'system')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum_old" USING "type"::"text"::"public"."notifications_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum_old" RENAME TO "notifications_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "sentAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "occurrenceAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "attempts"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "readAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetAttempts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aaf80b5186beed4e37b9ba7cb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c9dcc59e626ce14da4adbfc29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4907f15416577c3bbbcd604d12"`);
        await queryRunner.query(`DROP TABLE "event_participants"`);
        await queryRunner.query(`DROP TYPE "public"."event_participants_responsestatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dcd288f71e9aececacecd48a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69b9c4cb2cb4a6cf03bb035206"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a007ca3d443825b41461d9da45"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`DROP TYPE "public"."calendar_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."calendar_events_recurrencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."calendar_events_meetingmode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_970ffad745900038e0940bbc81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1447da1c15277f0d6e6bc306"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f11650589e0d7eb7430074c0ef"`);
        await queryRunner.query(`DROP TABLE "work_item_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82807b63980b71887811dd3e2b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abeae3c5eda0582b40f441724d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0af3ac60fd4ce701702a331f9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cb8969d4f4b12b18bfbefc373"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5389d5a18c0058c26f949c3ace"`);
        await queryRunner.query(`DROP TABLE "work_items"`);
        await queryRunner.query(`DROP TYPE "public"."work_items_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_items_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1199343c652931a1f14a8c0387"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bce318acbb09dabc770bc4991c"`);
        await queryRunner.query(`DROP TABLE "project_sprints"`);
        await queryRunner.query(`DROP TYPE "public"."project_sprints_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f3370a56d2658d30d7583cf12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de336dd3979a38724d58ae30d8"`);
        await queryRunner.query(`DROP TABLE "project_team_members"`);
        await queryRunner.query(`DROP TYPE "public"."project_team_members_accesslevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d71c230aff02473fe1ecb50942"`);
        await queryRunner.query(`DROP TABLE "project_teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63e67599567b2126cfef14e147"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_787ad05f1678689230c5e7f7b4"`);
        await queryRunner.query(`DROP TABLE "regularizations"`);
        await queryRunner.query(`DROP TYPE "public"."regularizations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d35666b9fca3fbfabba4c5ebb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b8da19d753f3f5cb79f4b6f2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_093560da4ec93f917bf26a1528"`);
        await queryRunner.query(`DROP TABLE "project_activity"`);
        await queryRunner.query(`DROP TYPE "public"."project_activity_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."project_activity_entitytype_enum"`);
    }

}
